from enum import StrEnum

class Requirement(StrEnum):
    TRIAL = "TRIAL"
    CONSULT_CODING = "CONSULT_CODING"
    ONLINE_CLASS = "ONLINE_CLASS"
    ENTREPRENEUR_CAMP = "ENTREPRENEUR_CAMP"
    TECHZANIA_CAMP = "TECHZANIA_CAMP"
    AI_CAMP = "AI_CAMP"
    DIGITAL_ART = "DIGITAL_ART"
    BOOK = "BOOK"
    FREE_INFORMATION = "FREE_INFORMATION"
    ABOUT_CODEKIDS = "ABOUT_CODEKIDS"
    IN_HOUSE = "IN_HOUSE"
    SUMMER_CAMP = "SUMMER_CAMP"
    OTHER = "OTHER"

class ContactType(StrEnum):
    INBOUND_ADS = "INBOUND_ADS"
    INBOUND_ORGANIC = "INBOUND_ORGANIC"
    OUTBOUND_FOLLOWUP = "OUTBOUND_FOLLOWUP"